steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/econoguide-backend'
      - '--build-arg'
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/econoguide-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'econoguide-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/econoguide-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'

images:
  - 'gcr.io/$PROJECT_ID/econoguide-backend'

substitutions:
  _GOOGLE_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY 